function throw_cpp_exception() {
    main_window.throw_exception();
}

throw_cpp_exception()

print("OK in uncaught_cpp_exception.js")
